package entity;

import java.util.Date;

public class Blog {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.id
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.categoryId
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	private Integer categoryid;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.title
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	private String title;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.titleIntro
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	private String titleintro;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.content
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	private String content;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.createdtime
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	private Date createdtime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column blog.md
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	private String md;
	
	private Category category;

	public Category getCategory() {
		return category;
	}

	public void setCategory(Category category) {
		this.category = category;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.id
	 * @return  the value of blog.id
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.id
	 * @param id  the value for blog.id
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.categoryId
	 * @return  the value of blog.categoryId
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	public Integer getCategoryid() {
		return categoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.categoryId
	 * @param categoryid  the value for blog.categoryId
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	public void setCategoryid(Integer categoryid) {
		this.categoryid = categoryid;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.title
	 * @return  the value of blog.title
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	public String getTitle() {
		return title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.title
	 * @param title  the value for blog.title
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	public void setTitle(String title) {
		this.title = title;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.titleIntro
	 * @return  the value of blog.titleIntro
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	public String getTitleintro() {
		return titleintro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.titleIntro
	 * @param titleintro  the value for blog.titleIntro
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	public void setTitleintro(String titleintro) {
		this.titleintro = titleintro;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.content
	 * @return  the value of blog.content
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	public String getContent() {
		return content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.content
	 * @param content  the value for blog.content
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	public void setContent(String content) {
		this.content = content;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.createdtime
	 * @return  the value of blog.createdtime
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	public Date getCreatedtime() {
		return createdtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.createdtime
	 * @param createdtime  the value for blog.createdtime
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	public void setCreatedtime(Date createdtime) {
		this.createdtime = createdtime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column blog.md
	 * @return  the value of blog.md
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	public String getMd() {
		return md;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column blog.md
	 * @param md  the value for blog.md
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	public void setMd(String md) {
		this.md = md;
	}
}