package mapping;

import entity.Blog;
import entity.BlogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface BlogMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	long countByExample(BlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	int deleteByExample(BlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	int insert(Blog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	int insertSelective(Blog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	List<Blog> selectByExampleWithBLOBs(BlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	List<Blog> selectByExample(BlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	Blog selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	int updateByExampleSelective(@Param("record") Blog record, @Param("example") BlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	int updateByExampleWithBLOBs(@Param("record") Blog record, @Param("example") BlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	int updateByExample(@Param("record") Blog record, @Param("example") BlogExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	int updateByPrimaryKeySelective(Blog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	int updateByPrimaryKeyWithBLOBs(Blog record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table blog
	 * @mbg.generated  Fri Dec 29 23:47:01 CST 2017
	 */
	int updateByPrimaryKey(Blog record);

    List<Blog> selectAll();
    
    // 新添加的方法
    List<Blog> selectByExampleWithCategory(BlogExample example);
    
    Blog selectByPrimaryKeyWithCategory(Integer id);
}